kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: frame-pod
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: frame-pod
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: frame-pod
  apiGroup: rbac.authorization.k8s.io