kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: frame-pod-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: frame-pod-rolebinding
subjects:
# - kind: Group
#   name: system:serviceaccounts
#   apiGroup: rbac.authorization.k8s.io

- kind: ServiceAccount
  name: testkube-api-server-tests-job
roleRef:
  kind: Role
  name: frame-pod-role
  apiGroup: rbac.authorization.k8s.io

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: frame-pod-rolebinding-default
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: frame-pod-role
  apiGroup: rbac.authorization.k8s.io