apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.Hostname}}-locust-exporter
  annotations:
    helm.sh/hook-weight: "4"
spec:
  manualSelector: true
  parallelism: 1
  selector:
    matchLabels:
      app: {{.Values.Hostname}}-locust-exporter
      tool: locust
  template:
    metadata:
      labels:
        app: {{.Values.Hostname}}-locust-exporter
        tool: locust
    spec:
      containers:
      - name: {{.Values.Hostname}}-locust-exporter-container
        image: containersol/locust_exporter
        imagePullPolicy: Always
        env:
        - name: LOCUST_EXPORTER_URI
          value: 'http://locust-master-svc-{{.Values.Hostname}}:8089'
        - name: LOCUST_METRIC_NAMESPACE
          value: '{{ .Release.Namespace }}'

        ports:
        - name: lcprom
          containerPort: 9646

      restartPolicy: OnFailure