apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Values.Hostname}}-locust-master-{{.Values.Rps}}rps-{{.Values.Vus}}vu
  annotations:
    helm.sh/hook-weight: "2"
spec:
  manualSelector: true
  parallelism: 1
  selector:
    matchLabels:
      app: {{.Values.Hostname}}-locust-master
  template:
    metadata:
      labels:
        app: {{.Values.Hostname}}-locust-master
    spec:
      volumes:
      - name: locust-test-script
        configMap:
          name: {{.Values.Hostname}}-locust-test
      containers:
      - name: locust-container
        image: locustio/locust
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.1"
        volumeMounts:
        - name: locust-test-script
          mountPath: /test_script/locustfile.py
          subPath: locustfile.py
        
        args: ["--master", "--autostart", "--autoquit", "5", "--expect-workers", "{{ .Values.Pods }}", "-f", "/test_script/locustfile.py", "--users", "{{.Values.Vus}}", "--spawn-rate", "{{.Values.Rate}}", "-H", "http://{{.Values.Ip}}:8000", "-t", "{{.Values.Duration}}", "--json", "--print-stats"]
      restartPolicy: OnFailure
