apiVersion: v1
kind: Service
metadata:
  name: {{.Values.Hostname}}-locust-master-svc
  annotations:
    helm.sh/hook-weight: "3"
spec:
  selector:
    app: {{.Values.Hostname}}-locust-master
  ports:
    - port: 8089
      name: web-ui
    - port: 5557
      name: worker-comm
    - port: 5558
      name: worker-comm-2