apiVersion: v2
dependencies:
- condition: testkube-operator.enabled
  name: testkube-operator
  repository: file://../testkube-operator
  version: 1.16.35
- condition: mongodb.enabled
  name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 13.10.1
- condition: testkube-api.nats.enabled
  name: nats
  repository: https://nats-io.github.io/k8s/helm/charts/
  version: 1.1.7
- name: testkube-api
  repository: file://../testkube-api
  version: 1.16.39
- condition: testkube-dashboard.enabled
  name: testkube-dashboard
  repository: file://../testkube-dashboard
  version: 1.16.7
- condition: global.features.logsV2
  name: testkube-logs
  repository: file://../testkube-logs
  version: 0.2.0
- name: global
  repository: file://../global
  version: 0.1.2
description: Testkube is an open-source platform that simplifies the deployment and
  management of automated testing infrastructure.
name: testkube
type: application
version: 1.16.63
