apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-{{ .Values.Rpm }}rpm-{{ .Values.Vus }}threads
spec:
  manualSelector: true
  parallelism: {{ .Values.Pods }}
  selector:
    matchLabels:
      app: jmeter
  template:
    metadata:
      labels:
        app: jmeter
    spec:
      volumes:
      - name: jmeter-test-script
        configMap:
          name: jmeter-test
      containers:
      - name: jmeter-container
        image: vaipali/my-first-repo:jmeter-distri-v0.2
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1"
            memory: 500Mi
        volumeMounts:
        - name: jmeter-test-script
          mountPath: /test_script/jmeter_test.jmx
          subPath: jmeter_test.jmx
        
        command: ["apache-jmeter-5.6.3/bin/jmeter-server"]
      restartPolicy: OnFailure
